### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by uzimith** [na2hiro/json-kifu-format#15]
将棋のWebアプリを書こうと思い調べていたところ、このプロジェクトを見つけました。
JSONで将棋の棋譜を取り扱うという素晴らしいプロジェクトで試してみたいと思ったんですが、`npm install json-kifu-format`などnpmなどのパッケージマネージャーでインストールできる訳ではないようです。

対応する予定はありませんか。

**Comment by na2hiro** [comment]
興味を持っていただきありがとうございます．
お返事が遅くなってすみません．開発に時間が割けない状況が続いています．
今後package.jsonの用意とnpmへの登録も行いたいと思っているのですが，一度これを行うとJKFの仕様の変更が難しくなるため，バージョン振りも含めて後回しになっていました．

ですがこれを使ってくださる方あるいは検討してくださる方がいる以上仕様も固定すべきかなと思います．
今月末に時間ができるのでその時に上記のプロセスを進めnpmの登録までを行いたいと思います．

**Comment by na2hiro** [comment]
https://www.npmjs.com/package/json-kifu-format
bc2a09a2cb6adcf9236089a9c0b081bcd4dcd043 までで無事npm登録にこぎつけました．お待たせして申し訳ありませんでした．
npm登録に至るまでに，曖昧だった仕様の決定及びバグの洗い出しを目的として，テストの整備をShogi.jsも含めて行いました．(#17)
今後も品質を高めていけるよう努力していきますのでよろしくお願いします．
