### ISSUE TITLE
CSA V2棋譜の読み込み不可

### ISSUE THREAD

**Issue by mizar** [na2hiro/json-kifu-format#27]
csa-parser.pegjs では、バージョン無しかV2.2の棋譜しか想定していないため、floodgateのV2棋譜を読み込めないようです。

http://wdoor.c.u-tokyo.ac.jp/shogi/view/latest-table.cgi?event=LATEST&filter=floodgate&show_self_play=1

http://wdoor.c.u-tokyo.ac.jp/shogi/floodgate.html

http://www.computer-shogi.org/protocol/

**Comment by na2hiro** [comment]
https://osdn.jp/projects/shogi-server/scm/git/shogi-server/blobs/1899be10b8b1ba8527c52036e4d7dc278fddbcc2/shogi_server/game.rb 確かにV2の棋譜を出力するようですね．対応します．

**Comment by na2hiro** [comment]
大変遅くなってしまいましたが対応しました．ご報告ありがとうございました． b544ea6f14baf72734ae4c20597e567c9283ca27
