### ISSUE TITLE
Support initial state "左七枚落ち", "右七枚落ち" as Kakinoki format

### ISSUE THREAD

**Issue by gemmaro** [na2hiro/json-kifu-format#39]
`README.md` says:

> `InitialPresetString = string` 平手，香落ち等KIFでサポートされている手合情報

And "[棋譜ファイルKIF形式](http://kakinoki.o.oo7.jp/kif_format.html) > ５．手合割" defines additional "左七枚落ち", "右七枚落ち."
So I think JKF should support them too.

**Comment by na2hiro** [comment]
> 2021/3/14 手合割に「左七枚落ち」と「右七枚落ち」を追加

Didn't know that. I'm going to add them

**Comment by na2hiro** [comment]
https://github.com/na2hiro/json-kifu-format/pull/54
