### ISSUE TITLE
Naming of "打"

### ISSUE THREAD

**Issue by gemmaro** [na2hiro/json-kifu-format#40]
Relate to [the `README.md`'s description](https://github.com/na2hiro/json-kifu-format#json%E3%81%AE%E5%BD%A2%E5%BC%8F-version-10):

> 打: H(Hit 何か違う気もする)

Based on the following two libraries, I think "Drop" would be more appropriate instead of "Hit". 

* [shogi-rs](https://nozaq.github.io/shogi-rs/shogi/moves/enum.Move.html#variant.Drop): `Drop`
* [elm-shogi](https://github.com/ewenig/elm-shogi/blob/7110d50034145fc6f0500bfe168d76de4518e2f3/src/Shogi/Types.elm#L30): `Drop`

However, this naming change may break compatibility.

**Comment by na2hiro** [comment]
Thanks for the suggestion. I got the word "drop" when I read source code of some computer shogi programs, which was a lot later than the time I defined this. At this point I think it's more important to keep the compatibility.

I should probably clarify that in the doc
