### ISSUE TITLE
[Question] Is the property omitted, or is it nullable?

### ISSUE THREAD

**Issue by gemmaro** [na2hiro/json-kifu-format#41]
In [JSONの形式 (Version 1.0)](https://github.com/na2hiro/json-kifu-format#json%E3%81%AE%E5%BD%A2%E5%BC%8F-version-10), it is explained as follows.

> "?"はない場合があるという意味です

Is the property omitted, or is it nullable? That is, Does the spec allow for both, or not, where property `aaa` is "?"?

```json
{}
```

```json
{ "aaa": null }
```

**Comment by na2hiro** [comment]
It means it's omitted like `{}`, which is similar to TypeScript's `?`.

**Comment by gemmaro** [comment]
While fixing draft JSON Schema file (#51 ), following error occured to `specification/files/ryuou201409020101.jkf.json` (which is symlinked from `test/files/jkf/ryuou201409020101.jkf` for [this constraint](https://github.com/na2hiro/json-kifu-format/pull/51#issuecomment-1036950496)):

```
specification/files/ryuou201409020101.jkf.json invalid
[
  {
    instancePath: '/moves/44/move/from',
    schemaPath: '#/$defs/placeFormat/type',
    keyword: 'type',
    params: { type: 'object' },
    message: 'must be object'
  }
]
```

According to your comment above, the existing JKF files (and possibly serializer, since it seems that they are generated automatically) is against the specification, I think.

**Comment by gemmaro** [comment]
In terms of JSON Schema, all options are possible 👍 
Based on the current game record files, the third option seems to be a good choice. (Since current json-kifu-format is v1.0 (initial version), so it sounds a bit strange to say it's for the historical reason.)

**Comment by na2hiro** [comment]
I see, makes sense. Let's go with the third option
