### ISSUE TITLE
dropEffectフィールドについて

### ISSUE THREAD

**Issue by gemmaro** [na2hiro/json-kifu-format#56]
`test/files/jkf/same_move_minimal.jkf` を調べているときに、 `dropEffect` フィールドがあることに気付きました。

```shell-session
$ jq '.moves[1].move.to' test/files/jkf/same_move_minimal.jkf
{
  "dropEffect": "move",
  "x": 7,
  "y": 6
}
```

このフィールドは同ファイルにしか存在せず、[JSONの形式 (Version 1.0)](https://github.com/na2hiro/json-kifu-format#json%E3%81%AE%E5%BD%A2%E5%BC%8F-version-10)でも言及されておりません。
このフィールドの存在は仕様に含まれますでしょうか。もし含まれましたら、フィールドの説明を仕様に追記いただけますと幸いです。もし含まれないようでしたら、JKFファイルを修正することになりそうです。

文脈： #51 によるJSON Schemaの作成中、 `test/files/jkf/*.jkf` との照らし合わせを行っています。

**Comment by na2hiro** [comment]
そのフィールドについて覚えがないのでなにかの間違いで混入したものと思われます。該当ファイルとスナップショットから消すのが妥当と思います。
